[project]
name = "reddit-big-data-ingestion"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.11.0",
    "faker>=37.8.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "ruff>=0.14.5",
]

[tool.ruff]
line-length = 86

# Tell ruff to use the standard flake8 rules.
# "F" = Pyflakes (e.g., unused imports)
# "E" = Pycodestyle (e.g., style errors)
select = ["E", "F"]